name: Build

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: leafo/gh-actions-lua@v5
      with:
        luaVersion: "5.1"
    - name: lua-releng
      run: wget --quiet --output-document - https://github.com/openresty/openresty-devel-utils/raw/master/lua-releng 2>/dev/null | perl

  compile:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: leafo/gh-actions-lua@v5
      with:
        luaVersion: luajit
    - name: luajit
      run: find $(pwd) -name "*.lua" -type f -exec luajit -bl {} > /dev/null \;
